build: false
version: "{branch}-{build}"

environment:
  PYTHON_PATH: C:\Python27

install:
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install .
test_script:
  - python setup.py test -q
